
Exception on /public/signup [POST]
Traceback (most recent call last):
  File "/home/foxcodenine/.local/share/virtualenvs/MyProjectDir-0jH5YnbY/lib/python3.8/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/foxcodenine/.local/share/virtualenvs/MyProjectDir-0jH5YnbY/lib/python3.8/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/foxcodenine/.local/share/virtualenvs/MyProjectDir-0jH5YnbY/lib/python3.8/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/foxcodenine/.local/share/virtualenvs/MyProjectDir-0jH5YnbY/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/foxcodenine/.local/share/virtualenvs/MyProjectDir-0jH5YnbY/lib/python3.8/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/foxcodenine/.local/share/virtualenvs/MyProjectDir-0jH5YnbY/lib/python3.8/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/media/foxcodenine/KINGSTON/Projects/research_n_study/python/flask_project_structure/MyProjectDir/app/module/views.py", line 39, in signup
    image_filename = photos.save(form.image.data)
  File "/home/foxcodenine/.local/share/virtualenvs/MyProjectDir-0jH5YnbY/lib/python3.8/site-packages/flask_uploads.py", line 422, in save
    os.makedirs(target_folder)
  File "/usr/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  [Previous line repeated 1 more time]
  File "/usr/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/var/www'
Exception on /public/signup [POST]
Traceback (most recent call last):
  File "/home/foxcodenine/.local/share/virtualenvs/MyProjectDir-0jH5YnbY/lib/python3.8/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/foxcodenine/.local/share/virtualenvs/MyProjectDir-0jH5YnbY/lib/python3.8/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/foxcodenine/.local/share/virtualenvs/MyProjectDir-0jH5YnbY/lib/python3.8/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/foxcodenine/.local/share/virtualenvs/MyProjectDir-0jH5YnbY/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/foxcodenine/.local/share/virtualenvs/MyProjectDir-0jH5YnbY/lib/python3.8/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/foxcodenine/.local/share/virtualenvs/MyProjectDir-0jH5YnbY/lib/python3.8/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/media/foxcodenine/KINGSTON/Projects/research_n_study/python/flask_project_structure/MyProjectDir/app/module/views.py", line 39, in signup
    image_filename = photos.save(form.image.data)
  File "/home/foxcodenine/.local/share/virtualenvs/MyProjectDir-0jH5YnbY/lib/python3.8/site-packages/flask_uploads.py", line 422, in save
    os.makedirs(target_folder)
  File "/usr/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  [Previous line repeated 1 more time]
  File "/usr/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/var/www'
